config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'static_pages#home'
  get '/home/:first_name', to: 'dynamic_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  resources :gossips do
    resources :like_gossips, only: [:create, :destroy]
  end

  resources :gossips do
    resources :comments
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

end


# gossips GET        /gossips(.:format)               gossips#index
# POST               /gossips(.:format)                gossips#create
# new_gossip GET     /gossips/new(.:format)            gossips#new
# edit_gossip GET    /gossips/:id/edit(.:format)         gossips#edit
# gossip GET         /gossips/:id(.:format)           gossips#show
# PATCH              /gossips/:id(.:format)         gossips#update
# PUT                /gossips/:id(.:format)           gossips#update
# DELETE             /gossips/:id(.:format)           gossips#destroy


# users GET         /users(.:format)             users#index
# POST              /users(.:format)             users#create
# new_user GET      /users/new(.:format)         users#new
# edit_user GET     /users/:id/edit(.:format)    users#edit
# user GET          /users/:id(.:format)         users#show
# PATCH             /users/:id(.:format)         users#update
# PUT               /users/:id(.:format)         users#update
# DELETE            /users/:id(.:format)         users#destroy

# cities GET        /cities(.:format)              cities#index
# POST              /cities(.:format)              cities#create
# new_city GET      /cities/new(.:format)          cities#new
# edit_city GET     /cities/:id/edit(.:format)     cities#edit
# city GET          /cities/:id(.:format)          cities#show
# PATCH             /cities/:id(.:format)          cities#update
# PUT               /cities/:id(.:format)          cities#update
# DELETE            /cities/:id(.:format)          cities#destroy

# gossip_comments GET       /gossips/:gossip_id/comments(.:format)                   comments#index
# POST                      /gossips/:gossip_id/comments(.:format)                   comments#create
# new_gossip_comment GET    /gossips/:gossip_id/comments/new(.:format)               comments#new
# edit_gossip_comment GET   /gossips/:gossip_id/comments/:id/edit(.:format)          comments#edit
# gossip_comment GET        /gossips/:gossip_id/comments/:id(.:format)               comments#show
# PATCH                     /gossips/:gossip_id/comments/:id(.:format)               comments#update
# PUT                       /gossips/:gossip_id/comments/:id(.:format)               comments#update
# DELETE                    /gossips/:gossip_id/comments/:id(.:format)               comments#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :like_comments
  validates :content, presence: true, length: { minimum: 3, maximum: 100 }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :like_gossips
  has_many :comments
  belongs_to :user
  
  validates :content, presence: true  
  validates :title, presence: true, length: { minimum: 3, maximum: 24 }
  validates :user, presence: true

end


 

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like_comment.rb
class LikeComment < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/like_gossip.rb
class LikeGossip < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :like_gossips
  has_many :like_comments
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :email
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])

    # trouver les gossips de la ville =>
    gossips = Gossip.all # on récupère tous les gossips existants
    @gossips_from_city = [] # on initialise notre liste vide 
    gossips.each do |gossip| # boucle for pour itérer sur les gossips
      if gossip.user.city == @city # on vérifie que le gossip appartient a notre ville
        @gossips_from_city << gossip # et on stock le gossip avant de tout renvoyer
      end
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    else
      @gossips = Gossip.all
    end
  end

  def new
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    else

      @gossip = Gossip.new
      @tags = Tag.all
    end

  end

  def show
    id = params[:id]
    @my_tags = []
    @gossip = Gossip.find(id)   
    @comment = Gossip.find(id).comments
    
    @tag_of_gossip = GossipTag.where(gossip: @gossip)
    @tag_of_gossip.each do |gossip_tag|
      @my_tags << Tag.find(gossip_tag.tag_id)
    end
    
  end

  def create
    @gossip_tags = []
    @gossip = Gossip.new(user: current_user, 
                         title: params[:title],
                         content: params[:content])

    @array_tags = params[:array_tag]

    if @array_tags.class == 'Array'
        @array_tags.each do |tag_id| 
          @gossip_tags << GossipTag.create(gossip: @gossip, tag: Tag.find(tag_id))
        end
    end

    if @gossip.save
      redirect_to '/gossips'
    else 
      render "#{new_gossip_path(@gossip)}"
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
    if @gossip.user != current_user
      redirect_to "/gossips/#{@gossip.id}"
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.user == current_user
      if @gossip.update(content: params[:new_content], title: params[:new_title])
        redirect_to @gossip
      else
        render :edit
      end
    else
      redirect_to "/gossips/#{@gossip.id}"
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.user == current_user
      @gossip.destroy
      redirect_to '/gossips'
    else
      redirect_to "/gossips/#{@gossip.id}"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id]) 
    end

    def new
        @cities = City.all 
        @user = User.new
    end

    def create
        @email = params[:email]
        @cities = City.all
        @first_name = params[:first_name]

        new_password = params[:password]
        confirm_password = params[:confirm_password]
        city = City.find(params[:city])

        @user = User.new(email: @email, city: city, password: new_password, password_confirmation: confirm_password, first_name: @first_name)
        if @user.save
            log_in(@user)
            redirect_to '/home'
        else
            render "#{new_user_path(@user)}"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def show_img(path)
        File.open("app/assets/images/#{path}", "rb") do |file|
          raw file.read
        end
      end
      def image_tag(path)
        File.open("app/assets/images/#{path}") do |file|
          raw file.read
        end
      end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_gossips_helper.rb
module LikeGossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<h1>Page de <%= @city.name %></h1>

<h3>Code postal : <%= @city.zip_code %></p>

<h2>Tous les gossips de la ville</h2>

<div class="container">
  <div class="row">
    <% @gossips_from_city.each do |gossip| %>
      <div class="col-md-4">
        <div class="my-3 p-3 bg-white rounded box-shadow">
          <h6 class="border-bottom border-gray pb-2 mb-0"> <%= gossip.user.first_name %> </h6>  
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark"><%= gossip.title %></strong>
            <%= gossip.content.truncate(20, omission: '...') %> <%= link_to "Voir plus", gossip_path(gossip.id) %></br>
            Comments : <%= gossip.comments.count %> | Likes : <%= gossip.like_gossips.count %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/edit.html.erb
<h1>Lâche ton doss'</h1>

<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à mettre à jour le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_tag url_for(action: 'update'), method: "patch" do %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <%= label_tag 'Quel est le contenu?' %>
  <p class="mt-5">Titre :</p>
  <%= text_field_tag :comment, @gossip.title, autocomplete: "off", class: "form-control", name: 'new_title'%>
  </br>
  <p>Gossip :</p>
  <%= text_area_tag :comment, @gossip.content, autocomplete: "off", class: "form-control",  name: 'new_content'%>
  <br>

  <%= submit_tag "Mettre à jour le potin" %>

<% end %>

app/views/gossips/index.html.erb
<div class="container">
  <div class="row">
  <% ordered_gossips = @gossips.order(created_at: :desc) %>
    <% ordered_gossips.each do |gossip| %>
      <div class="col-md-4">
        <div class="my-3 p-3 bg-white rounded box-shadow">
          <h6 class="border-bottom border-gray pb-2 mb-0"> Author : <%= link_to gossip.user.first_name, user_path(gossip.user), class: "author" %> </h6>  
          <p class="media-body pb-3 mb-0 small lh-125 center_svg border-bottom border-gray">
            <strong class="d-block text-gray-dark"> Title : <%= gossip.title %></strong>
            <%= gossip.content.truncate(20, omission: '...') %> <%= link_to "Voir plus", gossip_path(gossip.id) %></br>
            
            <svg src="<%= show_img("comments.svg") %>"></svg> <%= gossip.comments.count %> <svg src="<%= show_img("like.svg") %>"></svg> <%= gossip.like_gossips.count %>
            
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/new.html.erb
<h1 class="text-primary px-5 d-flex m-3 justify-content-center bg-image">WHAT A CRUNCHY GOSSIP !</h1>


<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <%end%>
      
<div class="container container_create">
    <%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="content_gossip">
      <%= label_tag '' %>
      <%= text_field_tag 'title', nil, placeholder: 'Title' %></br>
      <%= label_tag '' %>
      <%= text_area_tag 'content', nil, placeholder: 'Write your crunchy gossip...'%>
      <h4 class="text-primary px-5 d-flex m-3 justify-content-center bg-image">Choose some Hashtag</h4>
    </div>
    <div class="tag_gossip">
      <ul>
        <% @tags.each do |tag| %>
            <li>
              <%= check_box_tag 'array_tag[]', tag.id -%>
              <%= h tag.title -%>
            </li>
        <% end %>
      </ul>
    </div>

    <div class="input_class">
      <%= submit_tag "Créer un potin", class: 'btn btn-primary m-4' %>
    </div>
    <% end %>
</div>

app/views/gossips/show.html.erb
  <h1 class="text-primary px-5 d-flex m-3 justify-content-center bg-image">This is a Gossip from&nbsp <%= link_to @gossip.user.first_name, user_path(@gossip.user), class: "author" %></h3>

<div class="card w-75 box_gossip">
  <div class="card-body">
    <h5 class="card-title"> <%= @gossip.title %></h5>
    <p class="card-text"><%= @gossip.content %></p>
    <div class="row">
    <p>
    <svg src="<%= show_img("comments.svg") %>"></svg> <%= @gossip.comments.count %> <svg src="<%= show_img("like.svg") %>"></svg> <%= @gossip.like_gossips.count %> 
    </p>
      <% if @gossip.user == current_user %>
        <div class="btn-group">
          <%= link_to edit_gossip_path(@gossip), class: "btn edit_btn resize_btn btn-primary btn-sm" do %> Edit <% end %>   
          <%= button_to "Delete", @gossip, :method => :delete, class: "btn resize_btn btn-danger btn-sm", id: "delete_gossip_button" %>
        </div>
      <% else %>
      
        <% if current_user.like_gossips.exists?(gossip_id: @gossip.id) %>
          <%= button_to "Dislike", gossip_like_gossip_path(@gossip), form_authenticity_token: true, :method => :delete, class: "btn btn-dark", id: "unlike_gossip_button" %>
        <% else %>
          <%= button_to "Like", gossip_like_gossips_path(@gossip), form_authenticity_token: true, :method => :post, class: "btn btn-primary", id: "like_gossip_button" %>
        <% end %>
      <% end %>
    </div>
    
    <% @my_tags.each do |tag| %>
      <%= tag.title %>
    <% end %>
    <p class="mt-3">Created on <%= @gossip.created_at %> at <%= link_to @gossip.user.city.name, city_path(@gossip.user.city) %></p>

</div>

<!-- Add a comment to the gossip -->

<%= form_tag gossip_comments_path(@gossip), action: 'create', method: "post" do %> 
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <%= label_tag '' %>
  <%= text_field_tag 'content', @content, placeholder: 'Write your comment'%>
  <%= submit_tag "Post", class: "btn btn-primary m-2" %>
<% end %>

<% ordered_comment = @comment.order(created_at: :desc) %>
<% ordered_comment.each do |comment| %>
    <div class="card w-75 box_comment">
    <div class="card-body">
        <h5 class="card-title"> <%= comment.user.first_name %></h5>
        <p class="card-text"><%= comment.content %></p>
        <p class="mt-3 card-text">Created on <%= comment.created_at %> </p>
        <% if comment.user == current_user %>
        <div class="btn_comment">
        <%= link_to edit_gossip_comment_path(@gossip, comment), class: "btn btn-primary" do %> Edit <% end %>
        <%= button_to "Delete", gossip_comment_path(@gossip, comment), :method => :delete, class: "btn btn-danger", id: "delete_comment_button" %>
        </div>
        <% end %>
        </div>
    </div>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {

    // Adding event listener to all elements with the class 'btn-danger'
    var deleteCommentButtons = document.querySelectorAll('.btn.btn-danger');
    deleteCommentButtons.forEach(function(button) {
      button.addEventListener('click', function(event) {
        if (!confirm("Are you sure you want to delete this element?")) {
          event.preventDefault();
        }
      });
    });
  });
</script>

app/views/users/new.html.erb
<div class="banner6 d-flex justify-content-center py-5">
  <!-- Row  -->
  <div class="row">
    <div class="container">
      <div class="col-lg-6 align-justify-center pr-4 pl-0 contact-form">
      <% if @user.errors.any? %>
  <p>We couldn't create your account for the following reason(s) :</p>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <%end%>
        <div class="container d-flex flex-column justify-content-around">
          <h2 class="mb-3 font-weight-light">Get Register For Free</h2>
          <h6 class="subtitle font-weight-normal">Lorem ipsum dolor sit amet, adipiscing.</h6>
          <form class="mt-3" action="<%= users_path %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <div class="row">
              <div class="col-lg-12">
                <div class="form-group">
                  <input class="form-control" name="email" type="email" placeholder="Give your Email address" required>
                </div>
              </div>
              <div class="col-lg-12">
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <input class="form-control" name="password" type="password" placeholder="Create your password (Minimum 6 characters)" required>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <input class="form-control" name="confirm_password" type="password" placeholder="Confirm password" required>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="form-group">
                  <input class="form-control" name="first_name" type="first_name" placeholder="First Name" required>
                </div>
              </div>
              <div class="col-lg-12">
              <label for="cities">Choose a city :</label>
              <form id="cityform">
                <select id="cities" name="city">
                  <% @cities.each do |city| %>
                    <option value="<%= city.id %>"><%= city.name %></option>
                  <% end %>
                </select>
              </form>
              <div class="col-lg-12">
                <button type="submit" class="btn btn-md btn-block btn-danger-gradiant text-white border-0"><span> Create Account</span></button>
                <!--  -->
              </div>
            </div>
          </form>
          <div class="row">
            <div class="col-lg-12 text-center mt-4">
              <h6 class="font-weight-normal">Signup with Social Accounts</h6>
              <div class="row">
                <div class="col-lg-6 col-md-6">
                  <a href="https://www.youtube.com/watch?v=xvFZjo5PgG0" class="btn btn-block bg-facebook text-white mt-3">Facebook</a>
                </div>
                <div class="col-lg-6 col-md-6">
                  <a href="https://www.youtube.com/watch?v=xvFZjo5PgG0" class="btn btn-block bg-twitter text-white mt-3">Twitter</a>
                </div>
              </div>
            </div>
            <div class="col-lg-12 text-center mt-4">
              Already have an account? <a href="/sessions/new" class="text-danger">Sign In</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Profil de l'identifiant : <%= @user.id %></h1>

<p>Mon prénom : <%= @user.first_name %></p>
<p>Mon nom : <%= @user.last_name %></p>
<p>Ma ville : <%= link_to @user.city.name, city_path(@user.city) %></p>
<p>Mon âge : <%= @user.age %></p>
<p>Description : <%= @user.description %>
<p>Mon adresse mail : <%= @user.email %></p>
<p>Ma date d'inscription : <%= @user.created_at %></p>