config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'static_pages#home'
  get '/home/:first_name', to: 'dynamic_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/team', to: 'static_pages#team'
  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]

  resources :gossips do
    resources :like_gossips, only: [:create, :destroy]
  end

  resources :gossips do
    resources :comments
  end
  
  get "up" => "rails/health#show", as: :rails_health_check

end


# gossips GET        /gossips(.:format)               gossips#index
# POST               /gossips(.:format)                gossips#create
# new_gossip GET     /gossips/new(.:format)            gossips#new
# edit_gossip GET    /gossips/:id/edit(.:format)         gossips#edit
# gossip GET         /gossips/:id(.:format)           gossips#show
# PATCH              /gossips/:id(.:format)         gossips#update
# PUT                /gossips/:id(.:format)           gossips#update
# DELETE             /gossips/:id(.:format)           gossips#destroy


# users GET         /users(.:format)             users#index
# POST              /users(.:format)             users#create
# new_user GET      /users/new(.:format)         users#new
# edit_user GET     /users/:id/edit(.:format)    users#edit
# user GET          /users/:id(.:format)         users#show
# PATCH             /users/:id(.:format)         users#update
# PUT               /users/:id(.:format)         users#update
# DELETE            /users/:id(.:format)         users#destroy

# cities GET        /cities(.:format)              cities#index
# POST              /cities(.:format)              cities#create
# new_city GET      /cities/new(.:format)          cities#new
# edit_city GET     /cities/:id/edit(.:format)     cities#edit
# city GET          /cities/:id(.:format)          cities#show
# PATCH             /cities/:id(.:format)          cities#update
# PUT               /cities/:id(.:format)          cities#update
# DELETE            /cities/:id(.:format)          cities#destroy

# gossip_comments GET       /gossips/:gossip_id/comments(.:format)                   comments#index
# POST                      /gossips/:gossip_id/comments(.:format)                   comments#create
# new_gossip_comment GET    /gossips/:gossip_id/comments/new(.:format)               comments#new
# edit_gossip_comment GET   /gossips/:gossip_id/comments/:id/edit(.:format)          comments#edit
# gossip_comment GET        /gossips/:gossip_id/comments/:id(.:format)               comments#show
# PATCH                     /gossips/:gossip_id/comments/:id(.:format)               comments#update
# PUT                       /gossips/:gossip_id/comments/:id(.:format)               comments#update
# DELETE                    /gossips/:gossip_id/comments/:id(.:format)               comments#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  has_many :like_comments
  validates :content, presence: true, length: { minimum: 3, maximum: 100 }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :like_gossips
  has_many :comments
  belongs_to :user
  
  validates :content, presence: true  
  validates :title, presence: true, length: { minimum: 3, maximum: 24 }
  validates :user, presence: true

end


 

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like_comment.rb
class LikeComment < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/like_gossip.rb
class LikeGossip < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :like_gossips
  has_many :like_comments
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id]) 
    end

    def new
        @cities = City.all 
        @user = User.new
    end

    def create
        @email = params[:email]
        @cities = City.all
        @first_name = params[:first_name]

        new_password = params[:password]
        confirm_password = params[:confirm_password]
        city = City.find(params[:city])

        @user = User.new(email: @email, city: city, password: new_password, password_confirmation: confirm_password, first_name: @first_name)
        if @user.save
            log_in(@user)
            redirect_to '/home'
        else
            render "#{new_user_path(@user)}"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def show_img(path)
        File.open("app/assets/images/#{path}", "rb") do |file|
          raw file.read
        end
      end
      def image_tag(path)
        File.open("app/assets/images/#{path}") do |file|
          raw file.read
        end
      end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_gossips_helper.rb
module LikeGossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body data-turbo="false">
  <header>
  <div class="header1 position-relative">
  <div class="container">
    <!-- Header 1 code -->
    <nav class="navbar navbar-expand-lg h1-nav">
    <img src="https://i.ibb.co/0C3HwN4/TGP.png" alt="TGP" border="0" class="logo_nav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header1" aria-expanded="false" aria-label="Toggle navigation">
				<span class="icon-menu"></span>
			</button>
      <div class="collapse navbar-collapse" id="header1">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item active"><a class="nav-link" href="/home">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="/team">Team</a></li>
          <li class="nav-item"><a class="nav-link" href="/contact">Contact</a></li>
          <li class="nav-item"><a class="nav-link" href="/gossips/new">Create a Gossip</a></li>
          <li class="nav-item"><a class="nav-link" href="/gossips">Show Gossips</a></li>
          <div class="dropdown">
  <% if current_user %>
  <%= button_to "Disconnect", session_path(session.id), :method => :delete, class: "btn btn-outline-success"%></button>
    <% else %>
    <button class="btn btn-outline-success py-2 px-4 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Login / Sign Up
  </button>
    <ul class="dropdown-menu dropdown-menu-light">
      <li><a class="dropdown-item" href="/sessions/new">Login</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><a class="dropdown-item" href="/users/new">Sign Up</a></li>
    </ul>
  <% end %>
</div>
        </ul>
      </div>
    </nav>

    
    <!-- End Header 1 code -->
  </div>
</div>
</header>


<%= yield %>

<footer class="mt-auto  text-white-50">
<p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
</footer>
  </body>
</html>